### PR TITLE
9.0 migrate base phone

### PR DESCRIPTION
**Pull request by sla-subteno-it**
Hello,

There is an ongoing PR but it was never corrected, I preferred to start on migration done by Alexis and finish what he had done.

### CODE REVIEW

**Comment by sla-subteno-it** [comment]
Perhaps close this PR also : https://github.com/OCA/connector-telephony/pull/67

**Comment by cvinh** [comment]
I think there is a problem with point_of_sale : 

Steps to reproduce : 
- Install base_phone and point_of_sale modules
- Go to a pos session
- Select Customer and modify the phone number

I have a fix but it has to be tested by experts ;-)
I do a PR to your branch

**Comment by alexis-via** [comment]
:+1: code review and tests

**Comment by YannisPV** [comment]
:+1:

**Pull request merged**
