### PR TITLE
[12.0][IMP] add module for sending sms using odoo native module but with ovh

### PR DESCRIPTION
**Pull request by sebastienbeau**
This module use the sms odoo module and only implement the provider for OVH as alternative.

Depend on the PR : https://github.com/OCA/server-tools/pull/1861

### CODE REVIEW

**Comment by sebastienbeau** [comment]
rebased as dependency have been merged

**Comment by sebastienbeau** [comment]
@legalsylvain @bealdav

**Review by legalsylvain — APPROVED** [review]
Lgtm. Thanks ! (Code review, no test)

**Comment by sebastienbeau** [comment]
solve missing dependency travis is green now

**Review by bealdav — APPROVED** [review]

**Pull request merged**
