### PR TITLE
ported to 9.0

### PR DESCRIPTION
**Pull request by jmalinens**

### CODE REVIEW

**Comment by alexis-via** [comment]
I discover your PR just now. I was also working on porting to v9, but as my work was not ready, I didn't create the PR yet. My branch is here (and I have more uncommited work on my laptop):

https://github.com/akretion/connector-telephony/tree/9.0-port

Maybe it can help...

**Comment by jmalinens** [comment]
@alexis-via sorry, I didn't see Your reply. I don't have much time but we should make it into working state

**Comment by pedrobaeza** [comment]
Superseeded by https://github.com/OCA/connector-telephony/pull/83. Due to inactivity, I close.

**Comment by alexis-via** [comment]
In fact, this PR was not superseesed by PR #83, because this PR ports a lot of module to v9, not only base_phone.
But I'll take the interesting parts of this PR (and keep @jmalinens as author) for the full port to v9 that I'm preparing, and I'll compare it with @invitu's work (if they sign the CLA).

**Pull request closed without merging**
