### PR TITLE
Fix bug #17: don't raise by default on write/create

### PR DESCRIPTION
**Pull request by alexis-via**
As a consequence, we can have non E.164 values inside the phone/mobile/fax fields: in this case, we don't display an href link on the field and we don't display the Dial button.

Fix show old number on paging for fax field (the fix in PR  #13 only fixed the issue for the phone field, but the bug was also present in the fax field !)

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Don't you change the widget to add `raise_if_parse_fails` argument in interactive mode?

**Comment by alexis-via** [comment]
@pedrobaeza Yes, that's a very good idea. I don't know how to do that exactly.
Maybe a simple solution would be to do in the XML view:

```
        <field name="phone" position="attributes">
            <attribute name="widget">phone</attribute>
            <attribute name="context">{'raise_if_parse_fails': True}</attribute>
        </field>
```

and then read the context to get the raise_if_parse_fails in the inherit of write/create.

Did you have another idea ?

**Comment by pedrobaeza** [comment]
Yes, that is the only way I see, because you can't control it in JS. Let's do it via context, but you can keep the parameter, and look for context key on create/write and pass it as an argument to the method.

**Comment by alexis-via** [comment]
@pedrobaeza The solution I proposed in my previous comment didn't work (the context inside the "phone" field wasn't passed to create/write), but I added the context in the window action, and it works.

If we think this is the right solution, I would need to inherit the other window actions that contain phone numbers.

**Comment by pedrobaeza** [comment]
Yeah, I see. That's why I told about putting in the widget, but the reformatting occurs when saving, so it's a different flow.

If no one tells about another solution, we would have to do it that way.

**Comment by chafique-delli** [comment]
It's ok for me. :+1:

**Comment by alexis-via** [comment]
I use this branch in production on several odoo v8 systems :+1:

**Pull request merged**
