### PR TITLE
[MIG] [17.0] base_phone

### PR DESCRIPTION
**Pull request by Nikul-OSI**

### CODE REVIEW

**Comment by Nikul-OSI** [comment]
Hii @gurneyalex @alexis-via @PierrickBrun, Can you please review this PR?

**Review by flotho — APPROVED** [review]
functionnal test on runboat,
LGTM
thanks for the migration

**Comment by pedrobaeza** [comment]
Can you rebase and fix the conflicts?

**Comment by flotho** [comment]
ping @Nikul-OSI any chance to follow @pedrobaeza recommendations ?
regards

**Comment by Nikul-OSI** [comment]
Already migrated https://github.com/OCA/connector-telephony/pull/316

Closed

**Pull request closed without merging**
