### PR TITLE
[8.0] Add meta files

### PR DESCRIPTION
**Pull request by bwrsandman**

### CODE REVIEW

**Comment by yvaucher** [comment]
```
File "/home/travis/odoo-8.0/openerp/modules/module.py", line 77, in load_module

mod = imp.load_module('openerp.addons.' + module_part, f, path, descr)

File "/home/travis/build/OCA/connector-telephony/asterisk_click2dial/__init__.py", line 22, in <module>

from . import asterisk_click2dial

File "/home/travis/build/OCA/connector-telephony/asterisk_click2dial/asterisk_click2dial.py", line 26, in <module>

import phonenumbers

ImportError: No module named phonenumbers
```

**Comment by dreispt** [comment]
Now I seriously get to think it would be worth to add to the MQT the "smartness" to automatically install the `external_dependencies` in the module manifests...

**Comment by bwrsandman** [comment]
Honestly, I would prefer to put these imports in

``` python
try:
    import external_dep
except ImportError:
    external_dep = None
```

So using this repo doesn't force the instance to install phonenumbers

**Comment by pedrobaeza** [comment]
Why the repo has already files. Are these modules already migrated to v8?

**Comment by bwrsandman** [comment]
@pedrobaeza yes, see: https://code.launchpad.net/openerp-asterisk-connector

**Comment by pedrobaeza** [comment]
Ah, OK, so let's go with the metafiles, and then we fix Travis issues.

:+1:

**Comment by dreispt** [comment]
:+1:

**Comment by rvalyi** [comment]
:+1: LGTM

**Pull request merged**
