### PR TITLE
[revolution] Port from 8 to 9 + new fields.Phone archi

### PR DESCRIPTION
**Pull request by alexis-via**
I re-used some of the work of @jmalinens in his PR https://github.com/OCA/connector-telephony/pull/75 (I set his name in one of the commits)

Click2dial and one-click access on calling party form is already working fine (updated to work with Asterisk 13).

This is still a work in progress, but it should be finished on Monday evening.

### CODE REVIEW

**Comment by alexis-via** [comment]
OK, the port to v9 is ready and fully tested.

**Comment by alexis-via** [comment]
FYI, I'm currently evaluating the feasability to make the base_phone and asterisk_click2dial module compatible with the web/enterprise module. It would require a re-organisation of the JS code of base_phone and asterisk_click2dial. I started working on it: if that moves the JS code of base_phone/asterisk_click2dial in the right direction (re-organise JS code between the 2 modules, cleanup our JS code), that I'll commit my work in this branch ; otherwise, it will be just a "try" and I'll drop the idea and the code I'm currently writting.

**Comment by alexis-via** [comment]
All the original features should have been restored now... no it should be ready for review/merge.

**Comment by alexis-via** [comment]
This PR is ready to merge.

**Comment by alexis-via** [comment]
Travis is green, so it's really ready to merge now !

**Comment by sla-subteno-it** [comment]
👍

**Comment by alexis-via** [comment]
EDIT: I was writing a wrong statement. The bug #93 is fixed in my next commit... but we will need to understand why do_notify doesn't work here.

**Comment by alexis-via** [comment]
@christophdb As you are using the branch of this PR, could you approve it ? (As you may know, to merge an OCA PR, we are supposed to have 2 :+1:).

**Pull request merged**
