### PR TITLE
8.0 FIX bug #20 Multiple click2dial when previous click2dial failed

### PR DESCRIPTION
**Pull request by alexis-via**
Patch courtesy of agutierrezdapda : thanks for your contribution !

### CODE REVIEW

**Comment by alexis-via** [comment]
Patch tested on my home Asterisk server ; I confirm it fixes the issue :+1:

**Comment by pedrobaeza** [comment]
:+1:

**Comment by pedrobaeza** [comment]
Can you change the author of the commit?

**Comment by alexis-via** [comment]
I changed it in another PR

**Pull request closed without merging**
