### PR TITLE
8.0 new module ovh_telephony_connector

### PR DESCRIPTION
**Pull request by alexis-via**
Some code clean-up and re-organisation in the generic modules
Prepare the removal of the module asterisk_click2dial_crm

### CODE REVIEW

**Comment by alexis-via** [comment]
I still have to re-test the asterisk_click2dial module to check that I haven't broken anything. I'll do that on my home server tonight.

**Comment by chafique-delli** [comment]
Thanks Alexis for your work. :+1:

**Comment by alexis-via** [comment]
I tested the asterisk_click2dial module of this branch with my home asterisk server, and everything is working well, so there is no regression in the asterisk connector. :+1:

**Comment by bguillot** [comment]
:+1:

**Pull request merged**
