### PR TITLE
[16.0][MIG] sms_no_automatic_delete: Migration to 16.0

### PR DESCRIPTION
**Pull request by BernatPForgeFlow**
Standard migration from v14: https://github.com/OCA/connector-telephony/tree/14.0/sms_no_automatic_delete

### CODE REVIEW

**Review by LoisRForgeFlow — APPROVED** [review]
Code review :+1:

**Review by AaronHForgeFlow — APPROVED** [review]
LGTM

**Review by MiquelRForgeFlow — APPROVED** [review]

**Comment by thomaspaulb** [comment]
@OCA/connector-telephony-maintainers Merge please!

**Pull request merged**
