### PR TITLE
[MIG] base_phone: Migration to 13.0 

### PR DESCRIPTION
**Pull request by mimusica**
@alexis-via Can you review, please?
Btw the test failed because it claims that there are 2 variables that aren't being used: evt & r (in the phone_widget.js)

### CODE REVIEW

**Comment by mimusica** [comment]
@pedrobaeza can you review and share your findings (suggestions for improvement).

**Comment by pedrobaeza** [comment]
Sorry, I'm not a user of this module right now. @alexis-via can be a better reviewer.

**Comment by pedrobaeza** [comment]
Anyway, I see that you need to squash all your migration commits into one (leaving formatting one apart).

**Comment by mimusica** [comment]
Created a new  [PR#222](https://github.com/OCA/connector-telephony/pull/222)

**Pull request closed without merging**
