### PR TITLE
Freeswitch 8.0

### PR DESCRIPTION
**Pull request by treveradams**
This is 8.0 with freeswitch_click2dial and freeswitch_click2dial_crm. These are not tested. I do not have an Odoo 8.0 install. I have matched the changes to the rest of the code, so they should work.

### CODE REVIEW

**Comment by treveradams** [comment]
The remaining errors seem to be some formatting complaints, the fact that ESL module is only available if you build it as part of a FreeSWITCH installation, and complaining that geocoder isn't used when it is. Except for:

freeswitch_click2dial/freeswitch_click2dial.py:227:22: E901 SyntaxError: invalid syntax

This same line exists in the 7.0 version and doesn't give an error. I am not sure what is wrong and would appreciate any help in fixing it.

**Comment by treveradams** [comment]
The import but not used in the integration tests is not accurate. Import not at top of file is either because it is below a the start of file comment block, or in one case, is an optimization for the common case.

**Comment by treveradams** [comment]
The complaint about the really long line is about a comment where I thought the line should remain as is.

**Comment by blessendor** [comment]
Thanks to Trevor's quick responses and fixes, I have working integrated FreeSWITCH (with FusionPBX configurator) and OpenERP/odoo 8 as platform of my web site and CRM system.

**Comment by treveradams** [comment]
Alex, thank you so much for your help in tracking down the problems you found. Hopefully this is now useful to many more people and is more flexible in the environments it will work in.

**Comment by lattoh** [comment]
Hello,
I have Grandstream IPPBX 6202, and would like to know if this connecteur can work with.

Thanks and regards

**Comment by treveradams** [comment]
@lattoh, it works with FreeSWITCH. Any sip, verto (with some extensions), etc. end points/clients should work. If not, please let me know.

**Comment by lattoh** [comment]
Hello,

Ok, I install telephony connector on Odoo 8 on Ubuntu server16.04 LTS.

I have Grandstream IPPBX UCM 6202 base on Asterisk and some ipphone Grandstream on my network.

But only call from dial buttom on partner form work, other function such as showing name of partner on my ipphone and opening partner form do not work.

Please can you help me for that ??

Thanks and regards,

**Comment by lattoh** [comment]
Juste to tell you that I have AMI 2.7.0 on my IPPBX UCM 6202, and I do not know if my problem come from version of AMI.


Thanks

**Pull request closed without merging**
