### PR TITLE
[MIG] base_phone: Migration to 13.0

### PR DESCRIPTION
**Pull request by mimusica**
@alexis-via please review and share your remarks.
@pedrobaeza Cleaned up the git log history. Are you satisfied? :-)

### CODE REVIEW

**Comment by pedrobaeza** [comment]
I'm afraid not:

- Why all these commits? These are the ones I say you have to merge:
Selección_007
- Please don't insert merge commits that screws up any further git operation.

**Comment by mimusica** [comment]
@pedrobaeza I thought you where speaking about the multiple commits carrying the same name... I fixed those. And left alone the the other small commits as @sbidoul  asked me to do small time commits when I was working on the [oca-github-bot](https://github.com/OCA/oca-github-bot/pull/124#issuecomment-664248566)
Tell me when you guys have your nose pointing in the same direction and I'll modify it accordingly.

Kind regards

**Comment by pedrobaeza** [comment]
Well, obviously there are styles around OCA, and probably @sbidoul and mine are the most opposite in this topic, as I don't want commits and he wants a lot.

Anyway, my rationale about this is simple: don't commit something that is not valuable as individual. You have followed your path to get the module migrated, but that path is not worth probably for anyone reviewing the migration PR, and they only add noise when reviewing commit history. Sometimes is good to let commits while the PR is in review for showing the evolution (but now it's not even needed, as GitHub shows the diff between force pushes), but before merging, a squash is asked due to the same reasoning.

Think if your commits are valuable as independent entities or not. I don't see right now that value. One of my examples with separated commits that worth to be that way: https://github.com/OCA/contract/pull/533

Selección_008

All the needed steps for migrating the module has been done in one commit, but then I have added a feature, and such thing is separated in a commit, so you can review isolately.

**Comment by mimusica** [comment]
Thanks for the clear explanation, I'll fix it tomorrow.

**Comment by mimusica** [comment]
I've modified it and kept "[IMP] base_phone: black, isort, prettier" as prescribed in the [wiki](https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-13.0).
Can you explain to me why I keep running in to this:
image
I've changed the file locally, squashed all commits you've asked and did a _git push mimusica --mirror_

**Comment by pedrobaeza** [comment]
This is because you have an outdated branch that is not synchronized with base branch. You have to make a rebase over 13.0 branch for getting that base, and then fix conflict, committing in your same migration commit:

https://docs.github.com/en/github/using-git/resolving-merge-conflicts-after-a-git-rebase

**Comment by mimusica** [comment]
I hope I did it good this time

**Comment by pedrobaeza** [comment]
It seems so, thanks!

**Comment by woakes070048** [comment]
Is this going to be merged?

**Comment by mohbadar** [comment]
Hi, 

Is there any plan to migrate all modules in this repository to odoo 13 soon?

**Comment by alexis-via** [comment]
On my side, I plan to migrate most of the modules to v14, but not to v13.

**Comment by alexis-via** [comment]
But if this PR is fine with positive reviews, we can merge it.

**Review by sebastienbeau — APPROVED** [review]
LGTM (code review)

**Pull request merged**
