### PR TITLE
[16.0][MIG] crm_phone: Migration to 16.0

### PR DESCRIPTION
**Pull request by TelmoSuarezConinpe**
Standard migration.

This PR depends on https://github.com/OCA/connector-telephony/pull/300

Replaces https://github.com/OCA/connector-telephony/pull/301

### CODE REVIEW

**Comment by AlexPForgeFlow** [comment]
Hi @TelmoSuarezConinpe can you fix the tests?

**Comment by TelmoSuarezConinpe** [comment]
@AlexPForgeFlow Fixed.

**Comment by JasminSForgeFlow** [comment]
Hi @TelmoSuarezConinpe can you please rebase and fix conflicts?

**Comment by yibudak** [comment]
@pedrobaeza Is there an issue blocking the merge of this PR? I can fix it and open a new PR.

Edit: It looks like this module has some conflicts with OCA/crm/crm_phonecall module since they both define "crm.phonecall" model. Maybe we can remove the duplicated codes in this module and just keep the additional things like working with base_phone's reformat_all_phonenumbers wizard. What do you suggest?

**Comment by pedrobaeza** [comment]
Nobody reviewed it: https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#review

**Comment by yibudak** [comment]
@pedrobaeza What do you think about the conflict between this module and OCA/crm/crm_phonecall?

**Comment by pedrobaeza** [comment]
IMO, this one should disappear in favor of the OCA/crm one.

**Pull request closed without merging**
