### PR TITLE
[FIX] flake8 errors

### PR DESCRIPTION
**Pull request by damdam-s**

### CODE REVIEW

**Comment by guewen** [comment]
thanks :+1:

**Comment by pedrobaeza** [comment]
Can you check dependency problem in Travis to totally greenify this?

**Comment by damdam-s** [comment]
@pedrobaeza Seems there is a dependency on a non-OCA addon...

**Comment by pedrobaeza** [comment]
Uhm, I didn't find _web_action_request_ in any place. OK, for now :+1: and let's see if @alexis-via knows about this dependency

**Comment by yvaucher** [comment]
lint check is green :+1:

**Comment by alexis-via** [comment]
@pedrobaeza The dependency on web_action_request is explained in the description of the base_phone_popup module:

```
The module *web_action_request* can be downloaded with Mercurial:

hg clone http://bitbucket.org/anybox/web_action_request
```

web_action_request is the module that allows the automatic notification for incoming calls. It has been written by Jean-Sebastien Suzanne from Anybox, who helped me a lot to develop the base_phone_popup module. I told Jean-Sebastien to push his module to the OCA, but I don't know if he did it or made a PR somewhere.

**Comment by pedrobaeza** [comment]
OK, can you include then the module download in the Travis .yml file?

**Pull request merged**
