### PR TITLE
[MIG] 14.0 sms_ovh_http

### PR DESCRIPTION
**Pull request by PierrickBrun**
needs https://github.com/OCA/server-tools/pull/1949 

Based on https://github.com/OCA/connector-telephony/pull/244

### CODE REVIEW

**Comment by florian-dacosta** [comment]
Got an error on base_phone.

  File "/odoo/links/base_phone/wizard/reformat_all_phonenumbers.py", line 72, in run_reformat_all_phonenumbers
    action = self.env["ir.actions.act_window"].for_xml_id(
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/odoo/src/odoo/http.py", line 639, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo/src/odoo/http.py", line 315, in _handle_exception
    raise exception.with_traceback(None) from new_cause
AttributeError: 'ir.actions.act_window' object has no attribute 'for_xml_id'

**Comment by PierrickBrun** [comment]
@florian-dacosta rebased on https://github.com/OCA/connector-telephony/pull/244

**Comment by sebastienbeau** [comment]
@florian-dacosta @dreispt can you update you review

**Review by florian-dacosta — APPROVED** [review]
LGTM code review

**Review by sebastienbeau — APPROVED** [review]
Tested and run in prod

**Pull request merged**
